// Generated by node tools/generate-routes.cjs from the published catalogs.
export const routes = {
  "/": {
    "parent": null
  },
  "/about-us": {
    "parent": "/",
    "index": 0,
    "view": "cabinet",
    "title": "About Us"
  },
  "/about-us/view": {
    "parent": "/about-us",
    "index": 0,
    "view": "crt",
    "title": "About Us"
  },
  "/retro-handheld": {
    "parent": "/",
    "index": 1,
    "view": "cabinet",
    "title": "Retro Handheld"
  },
  "/retro-handheld/games": {
    "parent": "/retro-handheld",
    "index": 1,
    "view": "crt",
    "title": "Retro Handheld"
  },
  "/retro-handheld/games/bungee-pug": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "bungee-pug",
    "title": "Bungee-Pug"
  },
  "/retro-handheld/games/chrome-possum": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "chrome-possum",
    "title": "Chrome Possum"
  },
  "/retro-handheld/games/colonel-pool-noodle": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "colonel-pool-noodle",
    "title": "Colonel Pool Noodle"
  },
  "/retro-handheld/games/dont-get-caught": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "dont-get-caught",
    "title": "Don't Get Caught"
  },
  "/retro-handheld/games/fructose": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "fructose",
    "title": "FRUCTOSE"
  },
  "/retro-handheld/games/gravy-knuckles": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "gravy-knuckles",
    "title": "Gravy Knuckles"
  },
  "/retro-handheld/games/gutter-comet": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "gutter-comet",
    "title": "Gutter Comet"
  },
  "/retro-handheld/games/lint-trap": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "lint-trap",
    "title": "Lint-Trap"
  },
  "/retro-handheld/games/macrame": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "macrame",
    "title": "Macramé"
  },
  "/retro-handheld/games/night-pickle": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "night-pickle",
    "title": "Night Pickle"
  },
  "/retro-handheld/games/sewer-halo": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "sewer-halo",
    "title": "Sewer Halo"
  },
  "/retro-handheld/games/slothman": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "slothman",
    "title": "SlothMan"
  },
  "/retro-handheld/games/static-weasel": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "static-weasel",
    "title": "Static Weasel"
  },
  "/retro-handheld/games/super-sloth-man-2": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "super-sloth-man-2",
    "title": "Super Sloth Man 2"
  },
  "/retro-handheld/games/steve-the-super-speed-sloth": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "super-speed-sloth",
    "title": "Steve - The Super Speed Sloth"
  },
  "/retro-handheld/games/tectonic-terry": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "tectonic-terry",
    "title": "Tectonic Terry"
  },
  "/retro-handheld/games/the-caulker": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "the-caulker",
    "title": "The Caulker"
  },
  "/retro-handheld/games/pink-rampage": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "the-circus",
    "title": "Pink Rampage"
  },
  "/retro-handheld/games/moss-hammer": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "the-moss-hammer",
    "title": "Moss Hammer"
  },
  "/retro-handheld/games/the-nudibranch": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "the-nudibranch",
    "title": "The Nudibranch"
  },
  "/retro-handheld/games/sloth-kart-racing": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "sloth-kart-racing",
    "title": "Sloth Kart Racing"
  },
  "/retro-handheld/games/star-sloth-69": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "star-sloth-69",
    "title": "Star Sloth 69"
  },
  "/retro-handheld/games/the-legend-of-emcee": {
    "parent": "/retro-handheld/games",
    "index": 1,
    "view": "crt",
    "game": "the-legend-of-emcee",
    "title": "The Legend of Emcee"
  },
  "/retro-arcade": {
    "parent": "/",
    "index": 2,
    "view": "cabinet",
    "title": "Retro Arcade"
  },
  "/retro-arcade/games": {
    "parent": "/retro-arcade",
    "index": 2,
    "view": "crt",
    "title": "Retro Arcade"
  },
  "/retro-arcade/games/sloth-invaders": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "sloth-invaders",
    "title": "Sloth Invaders"
  },
  "/retro-arcade/games/sloth-run": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "sloth-run",
    "title": "Sloth Run"
  },
  "/retro-arcade/games/slothger": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "slothger",
    "title": "Slothger"
  },
  "/retro-arcade/games/slubble-slobble": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "slubble-slobble",
    "title": "Slubble Slobble"
  },
  "/retro-arcade/games/sofa-king-barrel-blitz": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "sofa-king-barrel-blitz",
    "title": "Sofa King Barrel Blitz"
  },
  "/retro-arcade/games/grand-theft-sloth": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "grand-theft-sloth",
    "title": "Grand Theft Sloth"
  },
  "/retro-arcade/games/the-sloth-king": {
    "parent": "/retro-arcade/games",
    "index": 2,
    "view": "crt",
    "game": "the-sloth-king",
    "title": "The Sloth King"
  },
  "/demo-arcade": {
    "parent": "/",
    "index": 3,
    "view": "cabinet",
    "title": "Demo Arcade"
  },
  "/demo-arcade/view": {
    "parent": "/demo-arcade",
    "index": 3,
    "view": "crt",
    "title": "Demo Arcade"
  },
  "/merch-shop": {
    "parent": "/",
    "index": 4,
    "view": "cabinet",
    "title": "Merch Shop"
  },
  "/merch-shop/view": {
    "parent": "/merch-shop",
    "index": 4,
    "view": "crt",
    "title": "Merch Shop"
  },
  "/links": {
    "parent": "/",
    "index": 5,
    "view": "cabinet",
    "title": "The Links"
  },
  "/links/view": {
    "parent": "/links",
    "index": 5,
    "view": "crt",
    "title": "The Links"
  },
  "/links/beach": {
    "parent": "/links/view",
    "index": 5,
    "view": "crt",
    "beach": true,
    "title": "Beach Break | The Links"
  },
  "/new-stuff": {
    "parent": "/",
    "index": 6,
    "view": "cabinet",
    "title": "New Stuff"
  },
  "/new-stuff/view": {
    "parent": "/new-stuff",
    "index": 6,
    "view": "crt",
    "title": "New Stuff"
  },
  "/coming-soon": {
    "parent": "/",
    "index": 7,
    "view": "cabinet",
    "title": "Coming Soon"
  },
  "/coming-soon/view": {
    "parent": "/coming-soon",
    "index": 7,
    "view": "crt",
    "title": "Coming Soon"
  },
  "/contact-us": {
    "parent": "/",
    "index": 8,
    "view": "cabinet",
    "title": "Contact Us"
  },
  "/contact-us/view": {
    "parent": "/contact-us",
    "index": 8,
    "view": "crt",
    "title": "Contact Us"
  }
};
