const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const routes = { '/': { parent: null } };
const cabinets = ['About Us', 'Retro Handheld', 'Retro Arcade', 'Demo Arcade', 'Merch Shop', 'The Links', 'New Stuff', 'Coming Soon', 'Contact Us'];
const slug = title => title.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
for (const [index, title] of cabinets.entries()) {
  const cabinet = title === 'The Links' ? 'links' : slug(title);
  const base = '/' + cabinet;
  routes[base] = { parent: '/', index, view: 'intro', title };
  const content = base + (index === 1 || index === 2 ? '/games' : '/view');
  routes[content] = { parent: base, index, view: 'crt', title };
  if (index === 5) routes[base + '/beach'] = { parent: content, index, view: 'crt', beach: true, title: 'Beach Break | The Links' };
  if (index === 1 || index === 2) {
    const games = JSON.parse(fs.readFileSync(path.join(root, 'assets', index === 1 ? 'handhelds' : 'retro-arcade', 'catalog.json')));
    for (const game of games.filter(game => game.url)) {
      const destination = content + '/' + slug(game.title);
      if (routes[destination]) throw new Error('Duplicate game route: ' + destination);
      routes[destination] = { parent: content, index, view: 'crt', game: game.id, title: game.title };
    }
  }
}
fs.writeFileSync(path.join(root, 'routes.js'), '// Generated by node tools/generate-routes.cjs from the published catalogs.\nexport const routes = ' + JSON.stringify(routes, null, 2) + ';\n');
for (const route of Object.keys(routes).filter(route => route !== '/')) {
  const dir = path.join(root, route.slice(1));
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Lucid Confusion Creations</title><style>html{background:#130b22;color:white}</style><script src="/route-bootstrap.js" defer></script></head><body><noscript>Enable JavaScript to explore the arcade. <a href="/">Home</a></noscript></body></html>\n');
}
console.log(`Generated ${Object.keys(routes).length - 1} shared-shell route entries.`);
